export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS';
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE';

export const SET_SESSION 	= 'SET_SESSION';
export const AUTH_CHECKED 	= 'AUTH_CHECKED';